name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services: 
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        run: |
          docker build -t swiftsci-backend .
          docker run --name swiftsci-backend -d -p 5000:5000 swiftsci-backend
      - name: Close the Docker Container
        run: |
          docker stop swiftsci-backend
        
        


