name: AWS EC2 Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  deploy:
      # needs: build-and-test
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kaane0169/swiftsci-ec2:latest

      - name: Retrieve and Run Docker Images on EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ec2-user@${{ secrets.EC2_HOST }} 'bash -s' << 'ENDSSH'

            if [ -x "$(command -v docker)" ]; then
              echo 'Docker is already installed.'
            else
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce
              sudo usermod -aG docker $USER
            fi
            docker pull kaane0169/swiftsci-ec2:latest
            docker stop swiftsci-ec2 || true
            docker rm swiftsci-ec2 || true
            docker run -d --name swiftsci-ec2 -p 80:5000 kaane0169/swiftsci-ec2

          ENDSSH

      